name: My First Workflow

on: push

jobs:
  build:                # âœ… Job name added here
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Welcome Message
        run: echo "My first Github actions job"

      - name: List Files
        run: ls

      - name: Read Files
        run: cat README.md



