name: My First Workflow

on: push

jobs:
  build:                # âœ… Job name added here
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: List and Read Files
        run: |
            echo "My first Github actions job"
            ls -ltra
            cat README.md
      - name: General ASCII Artwork
        run: cowsay -f dragon "RUN FOR COVER, I AM A DRAGON....RAWRR" >> dragon.txt #cowasay is a thord part library






