name: Generate ASCII Workflow

on:
  push

jobs:
  ascii-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "RUN FOR COVER, I AM A DRAGON....RAWRR" >> dragon.txt

      - name: Execute File exists
        run: grep -i "dragon" dragon.txt

      - name: Read file
        run: cat dragon.txt

      - name: Checkout Repo Files
        run: ls
