name: Generate ASCII Workflow

on:
  push

jobs:
  ascii-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: List files in workspace
        run: ls -ltra

      - name: Make script executable
        run: chmod +x ascii-script.sh

      - name: Run script
        run: ./ascii-script.sh